export enum ProcessingStep {
  UPLOAD = 'UPLOAD',
  SELECT_COLUMNS = 'SELECT_COLUMNS',
  CONFIRM_COLUMNS = 'CONFIRM_COLUMNS',
  SELECT_MODEL = 'SELECT_MODEL',
  PROCESSING = 'PROCESSING',
  COMPLETE = 'COMPLETE',
} 